kubeversion: 1.9.4
ports:
  - name: k8sapi
    port: 8443
  - name: grpc
    port: 32080
  - name: mongodb
    port: 32017
  - name: appservice
    port: 32000
  - name: nodeport
    port: 31000-31005
description: Cocktail mini Service
