apiVersion: v1
kind: ConfigMap
metadata:
  name: registcluster-script
  namespace: cocktail-system
  labels:
    app: registcluster-script
data:
  1-register-somac-cluster.sql: |-
    USE cocktail;

    INSERT INTO provider_account
    (provider_account_seq, provider_code, provider_name, description, account_group_id,
    account_use_type, api_account_id, api_account_password, use_yn, created, creator, updated, updater)
    VALUES(1, 'OPM', 'Default', 'Default provider', '', 'USER', '', '', 'Y', UTC_TIMESTAMP(), 1, UTC_TIMESTAMP(), 1);