kind: Service
apiVersion: v1
metadata:
  name: build
  namespace: cocktail-system
spec:
  selector:
    app: dind
  ports:
  - protocol: TCP
    port: 2375
    targetPort: 2375
---    
apiVersion: v1 
kind: Pod 
metadata: 
    name: dind
    namespace: cocktail-system
spec: 
    containers: 
      - name: dind-daemon 
        image: docker:stable-dind
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}