apiVersion: v1
kind: ConfigMap
metadata:
  name: registcluster-script
  namespace: cocktail-system
  labels:
    app: registcluster-script
data:
  1-register-somac-cluster.sql: |-
    USE cocktail;

    INSERT INTO provider_account
    (provider_account_seq, provider_code, provider_name, description, account_group_id,
    account_use_type, api_account_id, api_account_password, use_yn, created, creator, updated, updater)
    VALUES(1, 'OPM', 'minikube', 'minikube', '', 'USER', '', '', 'Y', UTC_TIMESTAMP(), 1, UTC_TIMESTAMP(), 1);

    INSERT INTO clusters
    (cluster_seq, provider_account_seq, cluster_type, cluster_name, description, region_code, cube_type, auth_type, api_url, api_key, api_secret, billing_group_id,
    client_auth_data, client_key_data, server_auth_data, node_port_supported, ingress_supported, loadbalancer_supported, persistent_volume_supported, ingress_host,
    node_port_url, node_port_range, k8s_version, monitoring_db_user, monitoring_db_password, monitoring_db_host, monitoring_db_port, use_yn , created, creator, updated, updater)
    VALUES(1, 1, 'CUBE', 'minikube', 'minikube', 'DEFAULT', 'MANAGED', 'CERT', 'https://kubernetes.default:443', 'admin', 'AdminPass', NULL, base64_encoding_data, base64_encoding_data, base64_encoding_data, 'Y', 'Y', 'N', 'Y', '127.0.0.1', '127.0.0.1', '30000-32767', '1.9.4', 'root', 'root', 'http://cocktail-monitoring.monitoring', 9004, 'Y' , UTC_TIMESTAMP(), 1, UTC_TIMESTAMP(), 1);
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cocktail-cmdb-pvc-mysqldata
  namespace: cocktail-system
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cocktail-cmdb
  namespace: cocktail-system
  labels:
    app: cocktail-cmdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cocktail-cmdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cocktail-cmdb
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - image: regi.acornsoft.io/cocktail-common/cocktail-sm-db-develop:2.3.1.B000027
        name: cocktail-cmdb-01
        ports:
        - containerPort: 3306
          name: port-cmdb
          protocol: TCP
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /cocktail-initdata.d
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: cocktail-cmdb-pvc-mysqldata
      - name: mysql-initdb
        configMap:
          name: registcluster-script
---
apiVersion: v1
kind: Service
metadata:
  name: cocktail-cmdb
  namespace: cocktail-system
  labels:
    app: cocktail-cmdb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: cocktail-cmdb