apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: prometheus
  name: prometheus-rules
  namespace: monitoring
data:
  alerts: |-
    groups:
    - name: prometheus.rules
      rules:
      - alert: FailedReload
  rules: |-
    groups:
      - name: kubernetes.rules
        rules: