apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    component: prometheus
  name: prometheus
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi