apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      smtp_smarthost: 'smtp.daum.net:465'
      smtp_from: 'vancheju@daum.net'
      smtp_auth_username: 'vancheju'
      smtp_auth_password: 'wjddb4dk@daum'
      smtp_require_tls: false
      slack_api_url: https://hooks.slack.com/services/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
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
    - name: default